name: Build 7daye

on: workflow_dispatch

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1

      - name: Build IModApi dependency
        run: |
          msbuild lib\IModApi\IModApi.csproj /p:Configuration=Release /t:Build /m

      - name: Build WelcomePlugin
        run: |
          msbuild src\WelcomePlugin.csproj /p:Configuration=Release /t:Build /m
