name: Build 7daye

on: workflow_dispatch

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1

      - name: Restore packages
        run: |
          dotnet restore src\WelcomePlugin.csproj

      - name: Build WelcomePlugin
        run: |
          dotnet build src\WelcomePlugin.csproj -c Release
